# XA CI - Alpha Build - 02

name: XACI

on:
  push:
    branches: [ build-2 ]
  pull_request:
    branches: [ build-2 ]

jobs:
  # This workflow contains a job called "integration"
  integration:
        # A strategy that defines different variations of an environment to run each job in.
    strategy:
      matrix:
        os: [ubuntu-latest] # Supports Mac/Windows/Linux
        node: [14]
    # The runners that the job will run on
    runs-on: ${{ matrix.os }}
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout master branch
        uses: actions/checkout@v2.3.3

      - name: Cache node_modules
        uses: actions/cache@v2.1.1
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: node_modules
          # An explicit key for restoring and saving the cache
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run ESLint
        run: yarn lint

#       - name: Run unit tests
#         run: yarn test:unit
